### ISSUE TITLE
Per contract tx limiter should block all calls to contracts in some cases

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1285]
If a deployer key is removed from the user deployer whitelist the contracts that were deployed with that key will no longer be throttled by the per contract limiter, need to fix this so those contracts can't be called at all once the deployer is removed.

**Comment by mukuls9971** [comment]
I discussed with Suhas, and two possible solutions: 
1. When a deployerkey is removed, all the contracts deployed by that deployer can be removed from registry, or
2. we can save another key(removedContracts) to track removed contracts in user-deployer-whitelist, so we can get that list in tx-limiterMiddleware and apply a check there. 
First one seems better to me. Please suggest @ParthDesai

**Comment by enlight** [comment]
Contracts shouldn't be removed from the registry, since technically they still exist.
Probably should just store a boolean in the UserDeployerWhitelist contract to indicate whether or not a deployer is active, and instead of deleting deployers just mark them inactive.

**Comment by mukuls9971** [comment]
So we should 
1. keep a list inactiveDeployerContracts in TxLimiter to track the inactive deployer contracts 
2. GetInactiveDeployerContracts() function to populate  inactiveDeployerContracts with expiry as ContractDataRefreshInterval 
3. And, check in middleware and block the transaction if contractAddress is present in this list

**Comment by ParthDesai** [comment]
@mukuls9971 yeah, we could do something along this line.

**Comment by ParthDesai** [comment]
@mukuls9971 What we need: 

```
1. Method in user_deployer_whitelist which removes the user deployer, this method adds the contracts deployed by the particular deployer to inactive contract collection. 
2. Method in user_deployer_whitelist to get this collection of inactive contract. 
3. Populate inactive contracts as a map in the middleware with specific expiry time. 
4. Add check in middleware and block the transaction if contractAddress is present in that list. 
```

Note: For 3rd and 4th step, we should be opting for similar mechanism as we opted for contractToTierMap.

**Comment by mukuls9971** [comment]
queries:
 1, 2 : I think we should make the deployerstate as active / inactive by changing the deployerState and generate this collection in GetInactiveDeployerContracts() func : which return map of contractAddr->bool
3: expiry as ContractDataRefreshInterval(no need to keep separate because it is also contractData) which will refresh the above map
4. this check should be before contractToTierMap check
@ParthDesai

**Comment by ParthDesai** [comment]
Agree with 3rd and 4th point. 

For 1 and 2nd Point: no point in marking active/inactive, once a deployer key is removed, very slim chance that same key will be added again.

**Comment by mukuls9971** [comment]
As discussed @ParthDesai 
1. keep a Map inactiveDeployerContracts contractAddr->bool in  TxLimiter to track the inactive deployer contracts: generate this collection in GetInactiveDeployerContracts() func
2. make the deployerstate as active / inactive by changing the deployerState 
3. expiry as ContractDataRefreshInterval(no need to keep separate because it is also contractData) which will refresh the above map
4. And, check in middleware and block the transaction if contractAddress is present in this list(this check should be before contractToTierMap check)
5. Changes in Add_user_deployer, remove_user_deployer, proto and loom-js 
6. frontend breaking changes may happen in this scenario(need to inform frontend for this)
7. Need to change GetContractTierMapping to return only active contract mapping 
I am going ahead with this understanding 
@enlight

**Comment by enlight** [comment]
> * Changes in Add_user_deployer, remove_user_deployer, proto and loom-js
> 
> * frontend breaking changes may happen in this scenario(need to inform frontend for this)

What breaking changes are you talking about, there's one field being added to UserDeployerState protobuf as I understand it, why would that break anything?

**Comment by ParthDesai** [comment]
@enlight we were hoping, we would also expose the flag to frontend, so it can display active/inactive key both.  This is breaking as in, we are modifying the interface and frontend need to change their code to filter out in-active contracts.

**Comment by enlight** [comment]
Filtering should happen in the contract, the request protobuf sent to the existing `GetUserDeployers` method in the `UserDeployerWhitelist` contract should be extended to include a boolean field `include_inactive`, if it's true then return both active & inactive accounts in the response, otherwise just return the active contracts.

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1298
