### ISSUE TITLE
Timing Issue When Running "loom run" with Gateway Reactors Enabled

### ISSUE THREAD

**Issue by phoorichet** [loomnetwork/loomchain#1331]
When running `loom run`, it calls `initQueryService` and `startGatewayReactors` respectively. The `initQueryService` function is non-blocking. When `startGatewayReactors` is run, it tries to connect to QueryServer. 

The issue happens when `startGatewayReactors` call `QueryServer` before `initQueryService`  finishes open the port and finalizes the service. Thus `loom run` returns error `connect: connection refused`. 

This issue is likely to happen when we're tring to run e2e test with multinode validators on a single host because sharing resources might causing the delay on `initQueryService`.

https://github.com/loomnetwork/loomchain/blob/ce05f2501eaa2caef910f3feafd45edb971b03a5/cmd/loom/loom.go#L412
https://github.com/loomnetwork/loomchain/blob/ce05f2501eaa2caef910f3feafd45edb971b03a5/cmd/loom/loom.go#L416

**Comment by enlight** [comment]
Yeah, we should wait for the QueryServer to spin up before starting up the gateway reactors.

**Comment by mukuls9971** [comment]
@Parth 
It says initQueryService is non-blocking, it is using go-routines while starting rpc_server.. 
1. why can’t we make it blocking? It will only add some latency while start-up, but it will save us from lot of concurrency bugs
2. if we want to make it working with non-blocking only, we should use channels, and there are 3 goroutines in rpc_server.go in line 45,89 and 107, I need to have the understanding that how are these related which should be made concurrent @enlight ,

3. I have always read that we should use goroutines with channels for concurrency controls  otherwise it will create undeterministic problems in future, plz give me your views on this.

**Comment by Parth** [comment]
You're still tagging the wrong Parth

**Comment by Parth** [comment]
also this might be worth a read: https://www.jtolio.com/2016/03/go-channels-are-bad-and-you-should-feel-bad/

**Comment by pathornteng** [comment]
@mukuls9971 
`GatewayReactors` and `QueryServer` are two independent services. Yes we can add some latency to alleviate the problem but it is not very efficient. The better way is to check the status of the `QueryServer` before starting `GatewayRefactors`.

**Comment by ParthDesai** [comment]
@mukuls9971 

1) These two are independent services, changing one to solve problem in other is not the right thing to do.

2) You dont need to understand what these go-routines are, since we are not in any case making changes to rpc server. Since, gateway reactor is at fault, it should be the one to change.

3) Channels are there, so you can control your go-routine somewhat. But it is only feasible when go-routine is doing any granular, app developer defined work. For rpc server this is not feasible. 

So, best idea is to do this: 
Before starting gateway server, try to ping the query server it points to. Once it starts, then you start gateway reactor. (Add some predefined timeout, so this does not wait indefinitely)
