### ISSUE TITLE
Add new QueryServer RPC method to fetch total staked amount

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1574]
We need a new `dpos_total_staked` RPC method that returns a simple JSON response containing the total staked amount. The response should be cached so the dpos contract doesn't need to be queried too often (perhaps once a minute at most).

**Comment by pathornteng** [comment]
Dashboard calculates total staked using the sum of each validator total delegation plus its whitelist amount but excluding whitelist amount of bootstrapping nodes. The problem is the bootstrapping node addresses are hard-coded here https://github.com/loomnetwork/dashboard/blob/b2ceea2b21f7620ca6a0b19e38ae8cd05d521f58/src/config/production.ts#L25
Unfortunately, DPOSv3 has no idea which validators are bootstrapping validators.

Here are some of the solutions:
1. make dpos_total_staked read a list of bootstrapping node addresses configurable from loom.yaml and exclude these validators' whitelist amounts.
2. add a bootstrapping field in DPOS candidate protobuf and add a command to set this flag

**Comment by enlight** [comment]
Yeah, just add the list of bootstrap nodes to `loom.yml`, in PlasmaChain builds default the list to the current PlasmaChain boostrap nodes.

**Comment by enlight** [comment]
Resolved by https://github.com/loomnetwork/loomchain/pull/1575
