### ISSUE TITLE
Implement a more space efficient IAVL store

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#620]
The current IAVL store uses up too much disk space by saving ever single version to disk. Some space can be reclaimed by deleting old versions from the IAVL store, however this appears to be very slow, as well as unreliable (with some keys going missing after old versions are deleted, even though they are still supposedly referenced by newer versions). So we need a better IAVL store that ideally doesn't need pruning at all,

Requirements:
- New IAVL store should only write to disk every N blocks, and store the intermediary versions in memory.
- New IAVL store must generate the same app hashes as the current IAVL store when replaying blocks.
- New IAVL store must write a new version to disk when processing the first block after startup.
  This is to make sure that if an app hash mismatch occurs shortly after deploying a new
  build we can rollback the app store to a version that can still be correctly processed
  by the new build.

Pulling this off will likely require forking the `iavl` package to create a hybrid MemDB & LevelDB backed IAVL tree.

**Comment by Sriep** [comment]
name | time | disk size | compact | ratio time | ratio size | ratio compact
-- | -- | -- | -- | -- | -- | --
nieve | 42.753808385 | 143878761 | 143437026 | 100 | 100 | 100
prune2 | 29.573169054 | 30786828 | 17272351 | 69 | 21 | 12
2xDB | 19.184488022 | 65335520 | 65475391 | 44 | 45 | 45
nieve | 48.419747945 | 143365210 | 142958643 | 100 | 100 | 100
prune2 | 37.845223968 | 23948230 | 17220831 | 78 | 16 | 12
Periodic | 38.798430762 | 36314539 | 18650820 | 80 | 25 | 13
CacheDepend | 35.99396027 | 29455756 | 19671531 | 74 | 20 | 13

**Comment by Sriep** [comment]
The 2xDB method forgets orphans along with the in-memory DB, rather than deletes them.  This process is much quicker, almost half the speed of other methods, but the disk datbase is 3-4 times the size; Suggesting that some orphans cannot be just forgotten but need to be explicitly deleted.
There is some suggestion that the CacheDependant method can give better uncompacted DB-size figures. It aims to reduce writes to disk by keeping as much work as available RAM allows in memory. 

First two methods available in all branches.
nieve - saves to disk every block. Keeps all versions.
prune - saves to disk every block. Deletes all but latest two versions.
prune acts as a control and allows the tests across the two branches to be better compared. Need to add seed to random fuzz-tests.
From `iavl-hack` branch.
2xDB. Tree has two dbs. Saves most blocks in a memory DB, but saves every 20th block to disk DB. Then clears the memory DB.
From `issue620` branch.
Periodic. Saves to disk every 100 blocks. Keeps every 20th version and deletes all other versions except latest two.
Cache dependant. Saves to disk when cache size exceeds 4000 at block end and if so cache gets reset to size 200. Keeps every 20th version and deletes all other versions except latest two.

The first free columns are raw values for time taken (s) and disk size before and after compacting (bytes)
* ratio time The percentage ratio to nieve of time taken. (100*test-time/nieve-time)
* ratio size The percentage ration to nieve of disk database size. (100*test-disk-size/nieve-disk-size)
* ratio compact The percentage ratio to nieve of compacted database size. (100*test-disk-size-after-compacting/niave-disk-size-after-compacting)
Some older data at https://github.com/loomnetwork/loomchain/pull/1229

**Comment by enlight** [comment]
Resolved.
